FROM jenkins/jenkins:latest

# Skip initial setup
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

USER root
RUN apt-get update \
      && apt-get install -y sudo \
      && apt-get install -y sudo libltdl-dev \
      && apt-get install -y python \
      && apt-get install -y python-pip

# User name and Password
ARG JENKINS_PASS
ARG JENKINS_USER

ENV JENKINS_USER: $JENKINS_USER
ENV JENKINS_PASS: $JENKINS_PASS